name: flutter_imc_local_storage
description: Desafio de projeto - Armazenando os Dados de IMC e Persistindo Localmente.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  path: ^1.8.3
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
